- name: Deploy Flask App
  hosts: webserver
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask

    - name: Copy Flask app
      copy:
        src: ../app/
        dest: /home/ubuntu/app/

    - name: Run Flask app
      shell: nohup python3 /home/ubuntu/app/app.py &      